[package]
name = "problems"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc255-d = { alias = "abc255_d", problem = "https://atcoder.jp/contests/abc255/tasks/abc255_d"}
abc136-d = { alias = "abc136_d", problem = "https://atcoder.jp/contests/abc136/tasks/abc136_d"}
abc213-c = { alias = "abc213_c", problem = "https://atcoder.jp/contests/abc213/tasks/abc213_c"}
abc186-d = { alias = "abc186_d", problem = "https://atcoder.jp/contests/abc186/tasks/abc186_d"}
abc180-d = { alias = "abc180_d", problem = "https://atcoder.jp/contests/abc180/tasks/abc180_d"}
abc229-d = { alias = "abc229_d", problem = "https://atcoder.jp/contests/abc229/tasks/abc229_d"}
abc146-c = { alias = "abc146_c", problem = "https://atcoder.jp/contests/abc146/tasks/abc146_c"}
jsc2021-d = { alias = "jsc2021_d", problem = "https://atcoder.jp/contests/jsc2021/tasks/jsc2021_d"}
abc264-c = { alias = "abc264_c", problem = "https://atcoder.jp/contests/abc264/tasks/abc264_c"}
abc211-d = { alias = "abc211_d", problem = "https://atcoder.jp/contests/abc211/tasks/abc211_d"}
abc215-d = { alias = "abc215_d", problem = "https://atcoder.jp/contests/abc215/tasks/abc215_d"}
abc169-d = { alias = "abc169_d", problem = "https://atcoder.jp/contests/abc169/tasks/abc169_d"}
abc162-d = { alias = "abc162_d", problem = "https://atcoder.jp/contests/abc162/tasks/abc162_d"}
abc177-d = { alias = "abc177_d", problem = "https://atcoder.jp/contests/abc177/tasks/abc177_d"}
abc276-e = { alias = "abc276_e", problem = "https://atcoder.jp/contests/abc276/tasks/abc276_e"}
abc191-c = { alias = "abc191_c", problem = "https://atcoder.jp/contests/abc191/tasks/abc191_c"}
abc216-d = { alias = "abc216_d", problem = "https://atcoder.jp/contests/abc216/tasks/abc216_d"}
abc225-d = { alias = "abc225_d", problem = "https://atcoder.jp/contests/abc225/tasks/abc225_d"}
abc279-d = { alias = "abc279_d", problem = "https://atcoder.jp/contests/abc279/tasks/abc279_d"}
abc167-d = { alias = "abc167_d", problem = "https://atcoder.jp/contests/abc167/tasks/abc167_d"}
abc201-c = { alias = "abc201_c", problem = "https://atcoder.jp/contests/abc201/tasks/abc201_c"}
abc189-d = { alias = "abc189_d", problem = "https://atcoder.jp/contests/abc189/tasks/abc189_d"}
abc287-d = { alias = "abc287_d", problem = "https://atcoder.jp/contests/abc287/tasks/abc287_d"}
abc129-c = { alias = "abc129_c", problem = "https://atcoder.jp/contests/abc129/tasks/abc129_c"}
abc290-d = { alias = "abc290_d", problem = "https://atcoder.jp/contests/abc290/tasks/abc290_d"}
abc294-e = { alias = "abc294_e", problem = "https://atcoder.jp/contests/abc294/tasks/abc294_e"}
abc217-d = { alias = "abc217_d", problem = "https://atcoder.jp/contests/abc217/tasks/abc217_d"}
abc190-c = { alias = "abc190_c", problem = "https://atcoder.jp/contests/abc190/tasks/abc190_c"}
abc303-d = { alias = "abc303_d", problem = "https://atcoder.jp/contests/abc303/tasks/abc303_d"}
abc168-d = { alias = "abc168_d", problem = "https://atcoder.jp/contests/abc168/tasks/abc168_d"}
abc272-d = { alias = "abc272_d", problem = "https://atcoder.jp/contests/abc272/tasks/abc272_d"}
abc128-c = { alias = "abc128_c", problem = "https://atcoder.jp/contests/abc128/tasks/abc128_c"}
abc193-d = { alias = "abc193_d", problem = "https://atcoder.jp/contests/abc193/tasks/abc193_d"}

[[bin]]
name = "abc255-d"
path = "./src/bin/abc255_d.rs"

[[bin]]
name = "abc136-d"
path = "src/bin/abc136_d.rs"

[[bin]]
name = "abc213-c"
path = "src/bin/abc213_c.rs"

[[bin]]
name = "abc186-d"
path = "src/bin/abc186_d.rs"

[[bin]]
name = "abc180-d"
path = "src/bin/abc180_d.rs"

[[bin]]
name = "abc229-d"
path = "src/bin/abc229_d.rs"

[[bin]]
name = "abc146-c"
path = "src/bin/abc146_c.rs"

[[bin]]
name = "jsc2021-d"
path = "src/bin/jsc2021_d.rs"

[[bin]]
name = "abc264-c"
path = "src/bin/abc264_c.rs"

[[bin]]
name = "abc211-d"
path = "src/bin/abc211_d.rs"

[[bin]]
name = "abc215-d"
path = "src/bin/abc215_d.rs"

[[bin]]
name = "abc169-d"
path = "src/bin/abc169_d.rs"

[[bin]]
name = "abc162-d"
path = "src/bin/abc162_d.rs"

[[bin]]
name = "abc177-d"
path = "src/bin/abc177_d.rs"

[[bin]]
name = "abc276-e"
path = "src/bin/abc276_e.rs"

[[bin]]
name = "abc191-c"
path = "src/bin/abc191_c.rs"

[[bin]]
name = "abc216-d"
path = "src/bin/abc216_d.rs"

[[bin]]
name = "abc225-d"
path = "src/bin/abc225_d.rs"

[[bin]]
name = "abc279-d"
path = "src/bin/abc279_d.rs"

[[bin]]
name = "abc167-d"
path = "src/bin/abc167_d.rs"

[[bin]]
name = "abc201-c"
path = "src/bin/abc201_c.rs"

[[bin]]
name = "abc189-d"
path = "src/bin/abc189_d.rs"

[[bin]]
name = "abc287-d"
path = "src/bin/abc287_d.rs"

[[bin]]
name = "abc129-c"
path = "src/bin/abc129_c.rs"

[[bin]]
name = "abc290-d"
path = "src/bin/abc290_d.rs"

[[bin]]
name = "abc294-e"
path = "src/bin/abc294_e.rs"

[[bin]]
name = "abc217-d"
path = "src/bin/abc217_d.rs"

[[bin]]
name = "abc190-c"
path = "src/bin/abc190_c.rs"

[[bin]]
name = "abc303-d"
path = "src/bin/abc303_d.rs"

[[bin]]
name = "abc168-d"
path = "src/bin/abc168_d.rs"

[[bin]]
name = "abc272-d"
path = "src/bin/abc272_d.rs"

[[bin]]
name = "abc128-c"
path = "src/bin/abc128_c.rs"

[[bin]]
name = "abc193-d"
path = "src/bin/abc193_d.rs"

[dependencies]
num = "=0.2.1"
num-bigint = "=0.2.6"
num-complex = "=0.2.4"
num-integer = "=0.1.42"
num-iter = "=0.1.40"
num-rational = "=0.2.4"
num-traits = "=0.2.11"
num-derive = "=0.3.0"
ndarray = "=0.13.0"
nalgebra = "=0.20.0"
alga = "=0.9.3"
libm = "=0.2.1"
rand = { version = "=0.7.3", features = ["small_rng"] }
getrandom = "=0.1.14"
rand_chacha = "=0.2.2"
rand_core = "=0.5.1"
rand_hc = "=0.2.0"
rand_pcg = "=0.2.1"
rand_distr = "=0.2.2"
petgraph = "=0.5.0"
indexmap = "=1.3.2"
regex = "=1.3.6"
lazy_static = "=1.4.0"
ordered-float = "=1.0.2"
ascii = "=1.0.0"
permutohedron = "=0.2.4"
superslice = "=1.0.0"
itertools = "=0.9.0"
itertools-num = "=0.1.3"
maplit = "=1.0.2"
either = "=1.5.3"
im-rc = "=14.3.0"
fixedbitset = "=0.2.0"
bitset-fixed = "=0.1.0"
proconio = { version = "=0.3.6", features = ["derive"] }
text_io = "=0.1.8"
whiteread = "=0.5.0"
rustc-hash = "=1.1.0"
smallvec = "=1.2.0"

[dev-dependencies]
